### ISSUE TITLE
WM: Allow Mech to know if it's been redirected

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#116]
petda...@gmail.com reported on Oct 29, 2007 

<pre>
I think I didn&#39;t see an easy way to ask &quot;was I
redirected?&quot; Also, the documentation that says that
if you want to do complex things with forms, you
should be reading up on HTML::Form might want to be
a bit clearer. I spent a bunch of time figuring out
how to find out what fields my forms had.

From: 	ask@develooper.com
FWIW: I&#39;d love to have this feature too. To be most useful to me it&#39;d be
able to return a list of
the URLs that redirected and which HTTP status they were redirected with.

</pre>

### Details

Imported from [Google Code issue 5](http://code.google.com/p/www-mechanize/issues/detail?id=5) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=5)

* **Type**:      Enhancement
* **Date**:      Oct 29, 2007
* **Reporter**:  petda...@gmail.com
* **Owner**:     petda...@gmail.com
* **Priority**:  Medium
* **Status**:    Accepted
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on Jul 6, 2009 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `-Type-Defect Type-Enhancement`

**petda...@gmail.com** commented on Apr 24, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**Comment by oalders** [comment]
The best way at this point would be to call `HTTP::Response::redirects()`.  A convenience method for this might be nice.  At the very least it could be documented.
