### ISSUE TITLE
WM: better explanation of how to click a radio button

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#117]
petda...@gmail.com reported on Nov 9, 2007 

<pre>
 WM docs: better explanation of how to click a radio button
</pre>

### Details

Imported from [Google Code issue 12](http://code.google.com/p/www-mechanize/issues/detail?id=12) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=12)

* **Type**:      Enhancement
* **Date**:      Nov 9, 2007
* **Reporter**:  petda...@gmail.com
* **Owner**:     petda...@gmail.com
* **Priority**:  Medium
* **Status**:    Accepted
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on Nov 9, 2007 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `-Type-Defect Type-Enhancement`

**petda...@gmail.com** commented on Jul 6, 2009 :

<pre>
(No comment was entered for this change.)
</pre>

* Summary : WM: better explanation of how to click a radio button
* Labels : `Component-Docs`

**petda...@gmail.com** commented on Apr 24, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**Comment by simbabque** [comment]
This does not appear to be relevant any more. Radio buttons are just inputs like any other input. We don't mention them specifically in the docs, but essentially they're normal inputs. You set them to a value, but we don't have special handling for them. I don't think that needs explaining.

**Comment by petdance** [comment]
I'm wondering if I was thinking of checkboxes, not radio buttons.  The `tick` method has always been confusing.

**Comment by oalders** [comment]
@petdance do you think this should be re-opened?

**Comment by petdance** [comment]
I don't have an opinion one way or the other.  The ticket is 13 years old and I don't know what the docs look like today.
