### ISSUE TITLE
WM: doesn't strip quotes from url in meta refresh

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#120]
petda...@gmail.com reported on Nov 9, 2007 

<pre>
Originally at <a href="http://rt.cpan.org/Ticket/Display.html?id=27751" rel="nofollow">http://rt.cpan.org/Ticket/Display.html?id=27751</a>

From:  	&quot;Krieg, Jeremy&quot; &lt;Jeremy.Krieg@youramigo.com&gt;
Download (untitled) [text/plain 506b]
I ran into a page which had a meta refresh tag looking something like as
follows:

&lt;meta content=&quot;0; url=&#39;<a href="http://www.mysite.com/&#39;" rel="nofollow">http://www.mysite.com/&#39;</a>&quot; http-equiv=&quot;refresh&quot;&gt;

Mechanize successfully parsed out the URL, however it did not strip the
single quotes from it. So when I went to follow the link, I ended up at:

<a href="http://www.mysite.com&#39;" rel="nofollow">http://www.origsite.com/&#39;http://www.mysite.com&#39;</a>

Firefox handles this correctly.

It would be nice if Mechanize stripped the quotes out too.

The version of Mechanize that I am reporting against is 1.18
</pre>

### Details

Imported from [Google Code issue 19](http://code.google.com/p/www-mechanize/issues/detail?id=19) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=19)

* **Type**:      Defect
* **Date**:      Nov 9, 2007
* **Reporter**:  petda...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    Accepted
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on Apr 24, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Owner : ---
* Labels : `WM`

**Comment by oalders** [comment]
This has been fixed:

```
$ cat refresh.html
<body>
  <meta content="0; url='http://www.mysite.com/'" http-equiv="refresh">
</body>
$ cat meta.pl
#!/usr/bin/env perl

use strict;
use warnings;

use Test::More;
use WWW::Mechanize ();
use URI::file ();

my $url = URI::file->new_abs('refresh.html');

my $mech = WWW::Mechanize->new;
$mech->get($url);
my $link = $mech->find_link( tag => 'meta' );

is( $link->url, 'http://www.mysite.com/');

done_testing();
$ prove meta.pl
meta.pl ..
ok 1
1..1
ok
All tests successful.
Files=1, Tests=1,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.14 cusr  0.02 csys =  0.19 CPU)
Result: PASS
```
