### ISSUE TITLE
WM: set a <SELECT> field to a value not represented in an <OPTION>

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#123]
petda...@gmail.com reported on Nov 9, 2007 

<pre>
From:  	&quot;Erik Rantapaa&quot; &lt;erantapaa@gmail.com&gt;
Download (untitled) [text/plain 319b]
Hi,

I like WWW::Mechanize a lot, but I&#39;d like to request one small feature...

it turns out I need to set a &lt;SELECT&gt; field to a value not represented
by an &lt;OPTION&gt; tag. The method -&gt;field(name, value) won&#39;t let me do
this. Can you add another method to by-pass that check or suggest
another work-around?

Thanks,

ER
</pre>

### Details

Imported from [Google Code issue 23](http://code.google.com/p/www-mechanize/issues/detail?id=23) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=23)

* **Type**:      Enhancement
* **Date**:      Nov 9, 2007
* **Reporter**:  petda...@gmail.com
* **Owner**:     petda...@gmail.com
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**HQZ...@gmail.com** commented on Mar 19, 2008 :

<pre>
I meet the same issue with your and the <SELECT> field have two diffrences state in 
perl when the tag of <SELECT> AND <SELECT multiple>. Could your tell me how to do it 
. 

Thanks

ER
</pre>

**petda...@gmail.com** commented on Apr 24, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**Comment by simbabque** [comment]
This has been possible for a while now. You can do `$mech->field( foo => 'bar' )` where there was no option `'bar'`.
