### ISSUE TITLE
WM: Hidden fields don't appear in current_form if their value=""

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#125]
petda...@gmail.com reported on Nov 9, 2007 

<pre>
From <a href="http://rt.cpan.org/Ticket/Display.html?id=18521" rel="nofollow">http://rt.cpan.org/Ticket/Display.html?id=18521</a>

Best way to show this is with an example:

In this HTML snippet:
&lt;form name=&quot;aspnetForm&quot; method=&quot;post&quot; action=&quot;Browse.aspx?
MyToken=632797078501515540&quot; id=&quot;aspnetForm&quot;&gt;
&lt;div&gt;
&lt;input type=&quot;hidden&quot; name=&quot;__EVENTTARGET&quot; id=&quot;__EVENTTARGET&quot; value=&quot;&quot; /&gt;
&lt;input type=&quot;hidden&quot; name=&quot;__EVENTARGUMENT&quot; id=&quot;__EVENTARGUMENT&quot; value=&quot;&quot; /&gt;
&lt;input type=&quot;hidden&quot; name=&quot;__VIEWSTATE&quot; id=&quot;__VIEWSTATE&quot; value=&quot;/wEPDwUJ&quot; /&gt;
&lt;/div&gt;
[...]
&lt;/form&gt;

One should see three fields in a $mech-&gt;current_form-&gt;dump, but one only sees
&quot;__VIEWSTATE&quot;.

And of course if one tries to do this:

$mech-&gt;set_fields( &#39;__EVENTTARGET&#39; =&gt; &#39;mynewvalue&#39; );

WWW::Mechanize dies:
No such field &#39;__EVENTTARGET&#39; at /Library/Perl/5.8.6/WWW/Mechanize.pm line 1178

I can see why this would be coded, because why store an empty hidden field?
In this case, the site uses javascript to set the field, so they include it
in the form as an empty
hiden field, then use JavaScript to fill in the value and do the submit
(hack hack).
</pre>

### Details

Imported from [Google Code issue 25](http://code.google.com/p/www-mechanize/issues/detail?id=25) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=25)

* **Type**:      Defect
* **Date**:      Nov 9, 2007
* **Reporter**:  petda...@gmail.com
* **Owner**:     petda...@gmail.com
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**rou...@gmail.com** commented on Mar 14, 2008 :

<pre>
Are there any known workarounds or fixes to this issue?
</pre>

**asender....@gmail.com** commented on Mar 18, 2010 :

<pre>
$mech->form_number(1)->push_input ('hidden', { id => '__EVENTTARGET',
                                                name =>
'__EVENTTARGET',
                                                value =>
'chkFileSystem'}); 

It really helped save me from pulling my hair out.

asender

On Oct 2 2008, 11:53 am, Eric <eric.har...@gmail.com> wrote:
> I upgraded Mechanize 1.34 and found a few issues.  One of the sites I
> use Mechanize for is a .NET application and I used to fill in the
> __EVENTTARGET and __EVENTARGUMENT using
> 
> $agent->field ('__EVENTTARGET', 'chkFileSystem');
> 
> This, however, crashes the script with a nasty message "No such field
> __EVENTTARGET ... "
> I had to change it to
> 
> $form->push_input ('hidden', { id => '__EVENTTARGET',
>                                                 name =>
> '__EVENTTARGET',
>                                                 value =>
> 'chkFileSystem'});
> 
> where form is the current form being populated.  Hopefully, this helps
> someone from pulling their hair out.
> 
> Then I found out that all my basic authentication has broken on all of
> my scripts.  I used to use
> 
> my $agent = WWW::Mechanize->new ();
> $agent->credentials ($blah, $blah2, $user => $password);
> $agent->get ($protected_page);
> 
> This now fails with
> 
> Use of uninitialized value in concatenation (.) or string at /usr/lib/
> perl5/site_perl/5.8.8/LWP/Authen/Basic.pm line 8.
> 
> I got a new libwww, and this doesn't fix the problem.  I finally found
> a way using Base64::encode  that was documented somewhere.
> 
>         my $agent = WWW::Mechanize->new();
>        my @args = (
>              Authorization => "Basic " .
>              MIME::Base64::encode( $USER . ':' . $PASSWORD )
>     );
> 
>         $agent->get( $protected_page", @args );
> 
> And this gives me the page, however, when I do a submit of a form on
> the page, I get HTTP 401.  Is there a way to pass the credentials or
> set the credentials for the site/page so I can submit the form?
> 
> So Mechanize gurus, how should I be accessing pages protected by basic
> authentication so that I can submit forms and work on them?  Does this
> version of Mechanize handle NTLM protected pages?  How can I do that?
</pre>

**petda...@gmail.com** commented on May 4, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**thyt...@gmail.com** commented on Mar 6, 2012 :

<pre>
<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEWFwKLzJLoBwKQvJPWDQKQvO/WDQKQvPvWDQKQvPfWDQKQvOPWDQKQvP/WDQKQvMvWDQKQvMfWDQL+tqPmDAKVn4GbCQKMpfaTCwKQvJPWDQKQvO/WDQKQvPvWDQKQvPfWDQKQvOPWDQKQvP/WDQKQvMvWDQKQvMfWDQL+tqPmDAKVn4GbCQKMpfaTC5Mp0D49tCrX0OwZwTEebzy2rPHK" />

please help
</pre>

**Comment by simbabque** [comment]
Fixed with PR #312.
