### ISSUE TITLE
WM: Document ->fields return values and error conditions

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#127]
petda...@gmail.com reported on Nov 9, 2007 

<pre>

For the -&gt;fields method, please document what the return values are for
this method, and what happens if -&gt;fields is called on a field name that
does not exist.
</pre>

### Details

Imported from [Google Code issue 27](http://code.google.com/p/www-mechanize/issues/detail?id=27) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=27)

* **Type**:      Enhancement
* **Date**:      Nov 9, 2007
* **Reporter**:  petda...@gmail.com
* **Owner**:     petda...@gmail.com
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on May 4, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**Comment by simbabque** [comment]
There does not seem to be a `->fields` method in Mechanize. In fact, there wasn't one in the code [the day after this ticket was raised](https://github.com/libwww-perl/WWW-Mechanize/blob/6bb71ee0f2cc0e15ec28be178c22bd4d58e93318/lib/WWW/Mechanize.pm).
