### ISSUE TITLE
WM: add_fields, delete_fields methods

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#128]
petda...@gmail.com reported on Nov 9, 2007 

<pre>
From Peter Scott at <a href="http://rt.cpan.org/Ticket/Display.html?id=16690" rel="nofollow">http://rt.cpan.org/Ticket/Display.html?id=16690</a>

</pre>

### Details

Imported from [Google Code issue 28](http://code.google.com/p/www-mechanize/issues/detail?id=28) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=28)

* **Type**:      Enhancement
* **Date**:      Nov 9, 2007
* **Reporter**:  petda...@gmail.com
* **Owner**:     petda...@gmail.com
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on Nov 20, 2008 :

<pre>
I like the idea, but it needs to be more arbitrary, not just hidden fields.
</pre>

**petda...@gmail.com** commented on May 4, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**Comment by oalders** [comment]
Too little information to go on.
