### ISSUE TITLE
WM: Problems filling out <select multiple>

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#132]
petda...@gmail.com reported on Nov 9, 2007 

<pre>
From <a href="http://rt.cpan.org/Ticket/Display.html?id=19034" rel="nofollow">http://rt.cpan.org/Ticket/Display.html?id=19034</a>

HTML::Form-&gt;value has trouble handling &lt;select multiple&gt; (see
<a href="http://rt.cpan.org/Ticket/Display.html?id=18962" rel="nofollow">http://rt.cpan.org/Ticket/Display.html?id=18962</a>). This in turn gives
WWW::Mechanize trouble. Attached is a test which demonstrates the
problem (place it in t/local). By having Mechanize use
HTML::Form-&gt;param the problem can be worked around but I don&#39;t know if
this is a good idea for all form values.

Its an HTML::Form bug but Mechanize should be aware of the problem.

</pre>

### Details

Imported from [Google Code issue 33](http://code.google.com/p/www-mechanize/issues/detail?id=33) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=33)

* **Type**:      Defect
* **Date**:      Nov 9, 2007
* **Reporter**:  petda...@gmail.com
* **Owner**:     petda...@gmail.com
* **Priority**:  Medium
* **Status**:    Accepted
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on May 4, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**cuddeb...@gmail.com** commented on Nov 21, 2011 :

<pre>
I believe I have encountered this problem also.
</pre>

**Comment by simbabque** [comment]
The test from the original RT ticket that @schwern raised now passes. I've got a PR ready for that. 

We got the RT ticket for the issue in HTML::Form imported to https://github.com/libwww-perl/WWW-Mechanize/issues/89, but HTML::Form has since been moved to its own repository. It looks like the code that handles this has not changed since this was raised, and I am not sure why the test passes.

**Comment by oalders** [comment]
Closed via #310.
