### ISSUE TITLE
WM: Select multiple field not being shown in Mechanize

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#133]
prasad...@gmail.com reported on Dec 13, 2007 

<pre>
<b>What steps will reproduce the problem?</b>
1. I have a HTML page which has 6 selects and last 2 are select mutiples.
The last select mutiple is not being shown into the Mechanize form dump.
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

<b>What version of the product are you using? On what operating system?</b>

I am working on Linux and using WWW-Mechanize 1.34.

<b>Please provide any additional information below.</b>

 
</pre>

### Details

Imported from [Google Code issue 41](http://code.google.com/p/www-mechanize/issues/detail?id=41) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=41)

* **Type**:      Defect
* **Date**:      Dec 13, 2007
* **Reporter**:  prasad...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on Mar 12, 2008 :

<pre>
(No comment was entered for this change.)
</pre>

* Summary : WM: Select multiple field not being shown in Mechanize

**jordan.m...@gmail.com** commented on Jul 10, 2008 :

<pre>
Works for me.  Attached is the document I used to test.
</pre>

**petda...@gmail.com** commented on May 4, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**Comment by simbabque** [comment]
This is the document the ticket talks about (from the archive).

```html

<html>
--
<head>
<title>Test Page</title>
</head>
<body>
<form>
<select type="select" name="select1">
<option value="1"></option>
<option value="2"></option>
<option value="3"></option>
<option value="4"></option>
</select>
<select type="select" name="select2">
<option value="1"></option>
<option value="2"></option>
<option value="3"></option>
<option value="4"></option>
</select>
<select type="select" name="select3">
<option value="1"></option>
<option value="2"></option>
<option value="3"></option>
<option value="4"></option>
</select>
<select type="select" name="select4">
<option value="1"></option>
<option value="2"></option>
<option value="3"></option>
<option value="4"></option>
</select>
<select type="select" name="multiselect1" multiple="multiple">
<option value="1"></option>
<option value="2"></option>
<option value="3"></option>
<option value="4"></option>
</select>
<select type="select" name="multiselect2" multiple="multiple">
<option value="1"></option>
<option value="2"></option>
<option value="3"></option>
<option value="4"></option>
</select>
</form>
</body>
</html>
```
