### ISSUE TITLE
WM: Live tests fail in China

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#138]
petda...@gmail.com reported on Apr 3, 2008 

<pre>

The tests for this module try to access wikipedia.org, which is blocked
in some countries (eg mainland China), resulting in false test failures.

Also the tests fail by timing out, so they take a long long long time...
</pre>

### Details

Imported from [Google Code issue 48](http://code.google.com/p/www-mechanize/issues/detail?id=48) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=48)

* **Type**:      Defect
* **Date**:      Apr 3, 2008
* **Reporter**:  petda...@gmail.com
* **Owner**:     petda...@gmail.com
* **Priority**:  Medium
* **Status**:    Accepted
* **Labels**:    `WM`

### Comments
**hael...@gmail.com** commented on Jun 20, 2008 :

<pre>
This is not just a geographical problem.  There are cases where people in any country
may want to install this module on a computer that has very limited access to the
public internet -- for example, for testing web applications running on internal
networks.

Perhaps the live tests could simply be skipped if the Wikipedia server cannot be
reached, and only fail if they reach the server but return incorrect results?
</pre>

**petda...@gmail.com** commented on Nov 25, 2008 :

<pre>
(No comment was entered for this change.)
</pre>

* Summary : WM: Live tests fail in China

**petda...@gmail.com** commented on May 4, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**mark.sto...@gmail.com** commented on Feb 1, 2013 :

<pre>
From Makefile.PL, it appears that only local tests are run default, and local and live tests have been split up. 

Does this Issue still apply?
</pre>

**Comment by oalders** [comment]
Live tests are now in `xt/author/live/`
