### ISSUE TITLE
WM: You can click radio buttons that don't exist

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#145]
petda...@gmail.com reported on Jun 11, 2009 

<pre>
Say you have a radio button, and it has two values, Y or N.  You can submit
the form with the value &quot;X&quot; if you want.  That&#39;s tragic.
</pre>

### Details

Imported from [Google Code issue 102](http://code.google.com/p/www-mechanize/issues/detail?id=102) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=102)

* **Type**:      Defect
* **Date**:      Jun 11, 2009
* **Reporter**:  petda...@gmail.com
* **Owner**:     petda...@gmail.com
* **Priority**:  Medium
* **Status**:    Accepted
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on Apr 24, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**Comment by oalders** [comment]
I believe `WWW::Mechanize->new( strict_forms => 1);` should now handle this.
