### ISSUE TITLE
Get doesn't return on https

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#149]
marlon.a...@gmail.com reported on Jul 14, 2009 

<pre>
<b>What steps will reproduce the problem?</b>
    my $url = &#39;<a href="http://web.archive.org/web/20130510123721/https://www.autocarcoolstuff.com/checkout.cfm&#39;;" rel="nofollow">https://www.autocarcoolstuff.com/checkout.cfm&#39;;</a>
    use WWW::Mechanize;
    my $mech = WWW::Mechanize-&gt;new(
        timeout =&gt; 10
    );

    $mech-&gt;get( $url );
    print $mech-&gt;status() . &quot;\n&quot;;

<b>What is the expected output? What do you see instead?</b>
never returns.

<b>What version of the product are you using? On what operating system?</b>
ubuntu
<b>Please provide any additional information below.</b>

</pre>

### Details

Imported from [Google Code issue 111](http://code.google.com/p/www-mechanize/issues/detail?id=111) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=111)

* **Type**:      Defect
* **Date**:      Jul 14, 2009
* **Reporter**:  marlon.a...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on Apr 24, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**mark.sto...@gmail.com** commented on Feb 1, 2013 :

<pre>
I could not reproduce this issue with the test below. I recommend this issue be closed:

use Test::More;

use WWW::Mechanize;
my $mech = WWW::Mechanize->new;
   $mech->get('https://www.google.com/');
is($mech->status,200, 'Correct status is returned for https calls');

done_testing;
~
</pre>

**marlon.a...@gmail.com** commented on Feb 2, 2013 :

<pre>
Hi,

This issue requires a timeout. It means, some sites with https doesn't respect the timeout timer.
</pre>

**Comment by oalders** [comment]
Don't think we can reproduce.
