### ISSUE TITLE
WM: Mech should complain if we try to assign a checkbox a value that it cannot handle

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#157]
petda...@gmail.com reported on Aug 31, 2009 

<pre>
I just spent an hour debugging a problem where I had been setting a
checkbox&#39;s value to something it could not be.  Mech should have warned me.
</pre>

### Details

Imported from [Google Code issue 125](http://code.google.com/p/www-mechanize/issues/detail?id=125) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=125)

* **Type**:      Defect
* **Date**:      Aug 31, 2009
* **Reporter**:  petda...@gmail.com
* **Owner**:     petda...@gmail.com
* **Priority**:  Medium
* **Status**:    Accepted
* **Labels**:    `WM`

**Comment by oalders** [comment]
`WWW::Mechanize->new( strict_forms => 1);` should catch this now.
