### ISSUE TITLE
Don't use "ge" for version comparison

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#163]
esert...@yahoo.de reported on Oct 11, 2009 

<pre>
In WWW::Mechanize&#39;s Makefile.PL I see some version comparisons using the
&quot;ge&quot; operator. This will fail in some distant future:

#!/usr/bin/perl -w
$ExtUtils::MakeMaker::VERSION = &#39;10.01&#39;;
if ( $ExtUtils::MakeMaker::VERSION ge &#39;6.45_01&#39; ) {
    warn &quot;yes&quot;;
} else {
    warn &quot;no&quot;;
}
__END__

Yes, I know, there are ugly warnings if comparing numerically against a
version with underscore. To fix this, users often do &quot;eval&quot; such a version
number:

$ perl -we &#39;$x = eval &quot;6.45_01&quot;; warn $x&#39;
6.4501 at -e line 1.

Regards,
    Slaven
</pre>

### Details

Imported from [Google Code issue 135](http://code.google.com/p/www-mechanize/issues/detail?id=135) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=135)

* **Type**:      Defect
* **Date**:      Oct 11, 2009
* **Reporter**:  esert...@yahoo.de
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on May 4, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**mark.sto...@gmail.com** commented on Feb 1, 2013 :

<pre>
I confirmed that this issue is still present in WWW::Mechanize 1.72.
</pre>

**Comment by oalders** [comment]
Fixed in 1.86 and likely much earlier as well. https://metacpan.org/source/OALDERS/WWW-Mechanize-1.86/Makefile.PL
