### ISSUE TITLE
WM: t/live/wikipedia.t test hangs indefinetely

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#170]
todd.bru...@gmail.com reported on Mar 17, 2010 

<pre>
<b>What steps will reproduce the problem?</b>
1. on system behind a proxy (must use proxy to access internet, 
http_proxy environment variable is correctly set.)
2. perl Makefile.PL
3. make
4. make test

<b>What is the expected output? What do you see instead?</b>

t/live/wikipedia.t ....... 1/15 Error GETing <a href="http://en.wikipedia.org/" rel="nofollow">http://en.wikipedia.org/</a>: Can&#39;t 
connect to en.wikipedia.org:80 (connect: timeout) at t/live/wikipedia.t line 
26
# Looks like you planned 15 tests but ran 2.
# Looks like your test exited with 110 just after 2.
t/live/wikipedia.t ....... Dubious, test returned 110 (wstat 28160, 0x6e00)
Failed 13/15 subtests  

<b>What version of the product are you using? On what operating system?</b>
WWW::Mechanize 1.60 via CPAN
Redhat Enterprise Linux 5

<b>Please provide any additional information below.</b>

</pre>

### Details

Imported from [Google Code issue 153](http://code.google.com/p/www-mechanize/issues/detail?id=153) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=153)

* **Type**:      Defect
* **Date**:      Mar 17, 2010
* **Reporter**:  todd.bru...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**todd.bru...@gmail.com** commented on Mar 18, 2010 :

<pre>
See Issue 154... Same issue, I believe
</pre>

**petda...@gmail.com** commented on Jun 9, 2010 :

<pre>
(No comment was entered for this change.)
</pre>

* Summary : WM: t/live/wikipedia.t test hangs indefinetely
* Labels : `WM`

**marc...@gmail.com** commented on Feb 21, 2011 :

<pre>
I confirm that adding either $ENV{HTTP_PROXY} or $ENV{http_proxy} to t/live/wikipedia.t solves the issue. Of course, don't forget to also set NO_PROXY='localhost, ...'.

Cheers,

  ^m'e
</pre>

**mark.sto...@gmail.com** commented on Feb 1, 2013 :

<pre>
So the proposed fix is to simply out add a timeout value to this test and possibly other live tests? It would still fail, but would avoid the pain of indefinite timeout. 

Seems like a patch like that would be welcome.
</pre>

**Comment by oalders** [comment]
This test has now been moved to `xt`, so it should no longer be an issue for end users.
