### ISSUE TITLE
get should use url_abs

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#173]
batman...@gmail.com reported on Apr 21, 2010 

<pre>
<b>What steps will reproduce the problem?</b>
1. my $u = $mech-&gt;find_link(...)
2. $mech-&gt;get(&quot;&lt;Another URL with a different base&gt;&quot;)
3. $mech-&gt;get($u); # Here it calls the wrong URL as the base name has changed

<b>What is the expected output? What do you see instead?</b>
I would expect #3 above to get the absolute URL of the URL I found before.

<b>What version of the product are you using? On what operating system?</b>
1.62 arch linux.

<b>Please provide any additional information below.</b>

</pre>

### Details

Imported from [Google Code issue 163](http://code.google.com/p/www-mechanize/issues/detail?id=163) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=163)

* **Type**:      Defect
* **Date**:      Apr 21, 2010
* **Reporter**:  batman...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on Apr 24, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**Comment by oalders** [comment]
I think using a relative URL is not surprising behaviour here.
