### ISSUE TITLE
The forms are not detected if the tag <form> is in the same line with the <body> tag

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#177]
elma...@gmail.com reported on Jun 19, 2010 

<pre>
#!/usr/bin/perl

use WWW::Mechanize;
my $mech = WWW::Mechanize-&gt;new(
		agent =&gt; &#39;SonyEricssonW995/R1DB Browser/NetFront/3.4 Profile/MIDP-2.1 Configuration/CLDC-1.1&#39;
	);

$url = &#39;http://mail.live.com&#39;;
$mech-&gt;get($url);
$mech-&gt;follow_link(n =&gt; 1);
print $mech-&gt;dump_forms();
print $mech-&gt;content();
</pre>

### Details

Imported from [Google Code issue 173](http://code.google.com/p/www-mechanize/issues/detail?id=173) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=173)

* **Type**:      Defect
* **Date**:      Jun 19, 2010
* **Reporter**:  elma...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on Apr 24, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**Comment by simbabque** [comment]
The bug in the title of this issue is not a bug. Parsing single line HTML works just fine.
