### ISSUE TITLE
"WWW::Mechanizeinstances" on man page

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#185]
jidanni reported on Dec 19, 2010 

<pre>
Man page has word glued together:

 ..standalone WWW::Mechanizeinstances have
           autocheck turned on

Debian
Package: libwww-mechanize-perl
Version: 1.66-1
File: /usr/share/man/man3/WWW::Mechanize.3pm.gz

</pre>

### Details

Imported from [Google Code issue 189](http://code.google.com/p/www-mechanize/issues/detail?id=189) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=189)

* **Type**:      Defect
* **Date**:      Dec 19, 2010
* **Reporter**:  jidanni
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on Apr 24, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**Comment by oalders** [comment]
Has been fixed.
