### ISSUE TITLE
Mention one should find_link before follow_link 

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#188]
jidanni reported on Dec 19, 2010 

<pre>
Mention on the man page that one should remember to check first,

do { get_all_blogs_on_this_page() }
  while ( $mech-&gt;find_link( text_regex =&gt; qr&#39;下一頁&#39; )
    &amp;&amp; $mech-&gt;follow_link( text_regex =&gt; qr&#39;下一頁&#39; ) );

unless one wants to get nasty Link Not Found fatal messages.

Perhaps even use the results of the check instead of finding a second time.
</pre>

### Details

Imported from [Google Code issue 192](http://code.google.com/p/www-mechanize/issues/detail?id=192) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=192)

* **Type**:      Defect
* **Date**:      Dec 19, 2010
* **Reporter**:  jidanni
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**petda...@gmail.com** commented on Dec 19, 2010 :

<pre>
Documentation patches welcome.  Better that the person who finds the docs confusing submit the changes to the docs.
</pre>

**jidanni** commented on Dec 19, 2010 :

<pre>
Say: if follow_link() fails to find the link, the program will terminate with "Link Not Found". Therefore be sure to test first with find_link() when in doubt.
</pre>

**petda...@gmail.com** commented on Apr 24, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**mark.sto...@gmail.com** commented on Feb 4, 2013 :

<pre>
I would rather that follow_link be modified to fail rather than die if the link can't be found. The diagnostics can clarify that the link can't be followed because it wasn't found, not because the link failed to return a "successful" response.
</pre>

**Comment by simbabque** [comment]
`follow_link()` now calls `find_link()` first, so this seems already solved.
