### ISSUE TITLE
tick() requires a value to be set

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#192]
jordan.m...@gmail.com reported on Apr 16, 2011 

<pre>
Steps to reproduce:
1. Have a form with a malformed checkbox input (with no value), such as &lt;input type=&quot;checkbox&quot; name=&quot;scene&quot; id=&quot;scene&quot;&gt;
2. Issue a $mech-&gt;tick(&#39;scene&#39;, &#39;&#39;);

Expected output: checkbox is ticked
Resulting output: checkbox is not ticked

This applies to most recent version of WWW::Mechanize on any operating system.
</pre>

### Details

Imported from [Google Code issue 203](http://code.google.com/p/www-mechanize/issues/detail?id=203) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=203)

* **Type**:      Defect
* **Date**:      Apr 16, 2011
* **Reporter**:  jordan.m...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**jordan.m...@gmail.com** commented on Apr 16, 2011 :

<pre>
A patch has been provided via Github.
</pre>

**petda...@gmail.com** commented on Apr 16, 2011 :

<pre>
To what repo?  Mech is not yet hosted on Github.
</pre>

**jordan.m...@gmail.com** commented on Apr 16, 2011 :

<pre>
Sorry, the patch is attached.
</pre>

**petda...@gmail.com** commented on Apr 24, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**Comment by simbabque** [comment]
This is the diff from the original ticket, [lifted off archive.org](https://web.archive.org/web/20130621114432/http://code.google.com/p/www-mechanize/issues/attachmentText?id=203&aid=1377484067229910101&name=www-mech-203.patch&token=SHqneXiBc7HD9QNdL-sO2PF_fME%3A1368151045486).

```
Index: lib/WWW/Mechanize.pm
--
===================================================================
--- lib/WWW/Mechanize.pm	(revision 712)
+++ lib/WWW/Mechanize.pm	(working copy)
@@ -1611,9 +1611,12 @@
=head2 $mech->tick( $name, $value [, $set] )
 
"Ticks" the first checkbox that has both the name and value associated
-with it on the current form.  Dies if there is no named check box for
-that value.  Passing in a false value as the third optional argument
-will cause the checkbox to be unticked.
+with it on the current form.  If there is no value to the input, just
+pass an empty string as the value.  Dies if there is no named checkbox
+for the value given, if a value is given.  Passing in a false value
+as the third optional argument will cause the checkbox to be unticked.
+The third value does not need to be set if you wish to merely tick the
+box.
 
=cut
 
@@ -1626,6 +1629,13 @@
# loop though all the inputs
my $index = 0;
while ( my $input = $self->current_form->find_input( $name, 'checkbox', $index ) ) {
+        # Sometimes the HTML is malformed and there is no value for the check
+        # box, so we just return if the value passed is an empty string
+        # (and the form input is found)
+        if ($value eq '') {
+            $input->value($set ? $value : undef);
+            return;
+        }
# Can't guarantee that the first element will be undef and the second
# element will be the right name
foreach my $val ($input->possible_values()) {
```
