### ISSUE TITLE
Make current_form a mutator

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#197]
colossus...@gmail.com reported on Aug 8, 2011 

<pre>
If the user needs to manually iterate through the forms to find the one in which they are interested, there should be a way to set the form of interest to mech&#39;s current_form. Currently one has to directly assign to $mech-&gt;{current_form}.
</pre>

### Details

Imported from [Google Code issue 215](http://code.google.com/p/www-mechanize/issues/detail?id=215) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=215)

* **Type**:      Defect
* **Date**:      Aug 8, 2011
* **Reporter**:  colossus...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New

**Comment by oalders** [comment]
I think this can be closed.  There are various `form_*()` methods which can be used to select a form.
