### ISSUE TITLE
Support for HTTP DELETE required

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#199]
dancr...@gmail.com reported on Oct 13, 2011 

<pre>
WWW::Mechanize support HTTP GET, PUT and POST, but not HTTP DELETE.

In the era of RESTful web applications, it&#39;s important to support HTTP DELETE as one of the 4 main verbs.

Currently using v1.70 on Windows and Linux
</pre>

### Details

Imported from [Google Code issue 219](http://code.google.com/p/www-mechanize/issues/detail?id=219) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=219)

* **Type**:      Defect
* **Date**:      Oct 13, 2011
* **Reporter**:  dancr...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New

### Comments
**dancr...@gmail.com** commented on Oct 13, 2011 :

<pre>
Should be as simple as adding the following to Mechanize.pm

=head2 $mech->delete( $uri, content => $content )

DELETEs I<$content> to $uri.  Returns an L<HTTP::Response> object.
I<$uri> can be a well-formed URI string, a L<URI> object, or a
L<WWW::Mechanize::Link> object.

=cut

sub delete {
    my $self = shift;
    my $uri = shift;

    $uri = $uri->url if ref($uri) eq 'WWW::Mechanize::Link';

    $uri = $self->base
            ? URI->new_abs( $uri, $self->base )
            : URI->new( $uri );

    # It appears we are returning a super-class method,
    # but it in turn calls the request() method here in Mechanize
    return $self->_SUPER_delete( $uri->as_string, @_ );
}

# Added until LWP::UserAgent has it.
sub _SUPER_delete {
    require HTTP::Request::Common;
    my($self, @parameters) = @_;
    my @suff = $self->_process_colonic_headers(\@parameters,1);
    return $self->request( HTTP::Request::Common::DELETE( @parameters ), @suff );
}
</pre>

**dancr...@gmail.com** commented on Oct 13, 2011 :

<pre>
Here's a patch file, based off 1.70
</pre>

**Comment by oalders** [comment]
LWP::UserAgent now has `delete`
