### ISSUE TITLE
Install fails on mac osx snow leopard

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#201]
asb.c...@gmail.com reported on Nov 22, 2011 

<pre>
<b>What steps will reproduce the problem?</b>
1. run cpan of the native perl (v5.10.0)
2. install WWW::Mechanize

<b>What is the expected output? What do you see instead?</b>
/usr/bin/make install  -- OK

<b>What version of the product are you using? On what operating system?</b>
perl v5.10.0, the native perl installation of mac osx snow leopard (10.6.8)

<b>Please provide any additional information below.</b>
please cf. attachment

The installation works fine for a selfmade perl v5.14.1, but I need it up and running with the native perl installation.
</pre>

### Details

Imported from [Google Code issue 224](http://code.google.com/p/www-mechanize/issues/detail?id=224) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=224)

* **Type**:      Defect
* **Date**:      Nov 22, 2011
* **Reporter**:  asb.c...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New

### Comments
**rob...@gmail.com** commented on Jan 12, 2012 :

<pre>
I have the same issue on CentOS Linux with Perl 5.8.8, so I think it has nothing to do with the OS.

Another user on the same machine using a local::lib install did not get test failures from an install made a few months ago, so I suspect it has something to do with an upgrade of a dependency, maybe the HTTP modules (as we use the same HTML parser modules).
</pre>

**Comment by oalders** [comment]
Closing.  Can re-open if it's an issue on later MacOS versions.
