### ISSUE TITLE
Install fails on OS X Lion

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#204]
m...@probably.co.uk reported on Dec 19, 2011 

<pre>
t/local/back.t fails during 404 test if your resolver returns an address for &#39;localhost&#39; that&#39;s not 127.0.0.1

Like:

MacBook:~$ grep new xx.pl 
my $server = HTTP::Daemon-&gt;new(LocalAddr =&gt; &#39;localhost&#39;) or die;
MacBook:~$ ./xx.pl 
$VAR1 = &#39;<a href="http://o2wirelessbox.lan:52303/&#39;" rel="nofollow">http://o2wirelessbox.lan:52303/&#39;;</a>

It&#39;s irrelevant if localhost is in /etc/hosts - Lion looks at DNS _then_ /etc/hosts. Annoyingly it appears you cannot change the resolution order on Lion either! This may even only occur with certain resolvers.

I hacked up a patch to the test just to see if I could get it to work ok on my laptop, and it does. That&#39;s attached. It may not be the most elegant solution ;)
</pre>

### Details

Imported from [Google Code issue 227](http://code.google.com/p/www-mechanize/issues/detail?id=227) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=227)

* **Type**:      Defect
* **Date**:      Dec 19, 2011
* **Reporter**:  m...@probably.co.uk
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New

**Comment by oalders** [comment]
Closing for now.  Can re-open if it happens on later MacOS versions.
