### ISSUE TITLE
Test t/live/encoding.t fails on 'http://oops-music.com/'

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#205]
arjen...@googlemail.com reported on Dec 21, 2011 

<pre>
<b>What steps will reproduce the problem?</b>

&#39;make test&#39; will fail on t/live/encoding.t because the encoding of the homepage of <a href="http://oops-music.com/" rel="nofollow">http://oops-music.com/</a> is not EUC-JP as expected in the test script, but has changed to UTF-8.

WWW-Mechanize-1.68
</pre>

### Details

Imported from [Google Code issue 228](http://code.google.com/p/www-mechanize/issues/detail?id=228) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=228)

* **Type**:      Defect
* **Date**:      Dec 21, 2011
* **Reporter**:  arjen...@googlemail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New

### Comments
**arjen...@googlemail.com** commented on Dec 21, 2011 :

<pre>
I just found out that in https://github.com/bestpractical/www-mechanize/commit/9e309b49eef2b40a9c1e61dc9dbaf5f4725284c8 the test already has been removed.
</pre>

**Comment by sergeyromanov** [comment]
This issue can be resolved, based on the imported comment above:

https://github.com/libwww-perl/WWW-Mechanize/commit/9e309b49eef2b40a9c1e61dc9dbaf5f4725284c8

**Comment by oalders** [comment]
Closing. Thanks @sergeyromanov!
