### ISSUE TITLE
tes get_ok.t failing

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#208]
Zivildie...@gmail.com reported on Feb 26, 2012 

<pre>
test fails when trying to install Test::WWW::Mechanize

Perl 5.14.2
Debian 6.04

#   Failed test &#39;sanity check: we can&#39;t load NONEXISTENT.html&#39;
#   at t/get_ok.t line 44.

#   Failed test &#39;Fails to get nonexistent URI and reports failure&#39;
#   at t/get_ok.t line 51.
# STDOUT is:
# ok 1 - Try to get bad URL
#
# not:
# not ok 1 - Try to get bad URL
#
# as expected
# STDERR is:
#
# not:
# /#\s+Failed\ test.*?\n?.*?at\ t\/get_ok\.t line 50.*\n?/
#
# # 500
#
# # Can&#39;t connect to wango.nonexistent.xx-only-testing:80 (Bad hostname)
#
# as expected

#   Failed test &#39;And the result should be false&#39;
#   at t/get_ok.t line 54.
t/get_ok.t .................
Failed 3/11 subtests

# perl -V
Summary of my perl5 (<a href="/web/20130621055842/p/www-mechanize/source/detail?r=5">revision 5</a> version 14 subversion 2) configuration:

  Platform:
    osname=linux, osvers=2.6.32-5-amd64, archname=x86_64-linux
    uname=&#39;linux kvm6 2.6.32-5-amd64 #1 smp mon jan 16 16:22:28 utc 2012 x86_64 gnulinux &#39;
    config_args=&#39;-de -Dprefix=/opt/perlbrew/perls/perl-5.14.2&#39;
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef

  Compiler:
    cc=&#39;cc&#39;, ccflags =&#39;-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64&#39;,
    optimize=&#39;-O2&#39;,
    cppflags=&#39;-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include&#39;
    ccversion=&#39;&#39;, gccversion=&#39;4.4.5&#39;, gccosandvers=&#39;&#39;
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype=&#39;long&#39;, ivsize=8, nvtype=&#39;double&#39;, nvsize=8, Off_t=&#39;off_t&#39;, lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld=&#39;cc&#39;, ldflags =&#39; -fstack-protector -L/usr/local/lib&#39;
    libpth=/usr/local/lib /lib/../lib /usr/lib/../lib /lib /usr/lib /lib64 /usr/lib64
    libs=-lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.11.3.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version=&#39;2.11.3&#39;
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=&#39;-Wl,-E&#39;
    cccdlflags=&#39;-fPIC&#39;, lddlflags=&#39;-shared -O2 -L/usr/local/lib -fstack-protector&#39;

Characteristics of this binary (from libperl): 
  Compile-time options: PERL_DONT_CREATE_GVSV PERL_MALLOC_WRAP
                        PERL_PRESERVE_IVUV USE_64_BIT_ALL USE_64_BIT_INT
                        USE_LARGE_FILES USE_PERLIO USE_PERL_ATOF
  Built under linux
  Compiled at Feb 19 2012 16:40:50
  %ENV:
    PERLBREW_BASHRC_VERSION=&quot;0.41&quot;
    PERLBREW_HOME=&quot;/root/.perlbrew&quot;
    PERLBREW_MANPATH=&quot;/opt/perlbrew/perls/perl-5.14.2/man&quot;
    PERLBREW_PATH=&quot;/opt/perlbrew/bin:/opt/perlbrew/perls/perl-5.14.2/bin&quot;
    PERLBREW_PERL=&quot;perl-5.14.2&quot;
    PERLBREW_ROOT=&quot;/opt/perlbrew&quot;
    PERLBREW_VERSION=&quot;0.41&quot;
  @INC:
    /opt/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2/x86_64-linux
    /opt/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2
    /opt/perlbrew/perls/perl-5.14.2/lib/5.14.2/x86_64-linux
    /opt/perlbrew/perls/perl-5.14.2/lib/5.14.2

</pre>

### Details

Imported from [Google Code issue 231](http://code.google.com/p/www-mechanize/issues/detail?id=231) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=231)

* **Type**:      Defect
* **Date**:      Feb 26, 2012
* **Reporter**:  Zivildie...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New

### Comments
**Zivildie...@gmail.com** commented on Feb 26, 2012 :

<pre>
Turns out if I request http://wango.nonexistent.xx-only-testing/ on my server I get my apaches default page. No idea why but this issue report can be closed.
</pre>

**Comment by oalders** [comment]
Closing:

> Turns out if I request http://wango.nonexistent.xx-only-testing/ on my server I get my apaches default page. No idea why but this issue report can be closed.
