### ISSUE TITLE
Please add support for the DELETE method.

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#209]
ccolu...@gmail.com reported on Mar 8, 2012 

<pre>
<b>What steps will reproduce the problem?</b>
1. Try calling method DELETE
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
DELETE is not currently supported

<b>What version of the product are you using? On what operating system?</b>
1.72 linux centos 6

<b>Please provide any additional information below.</b>

</pre>

### Details

Imported from [Google Code issue 232](http://code.google.com/p/www-mechanize/issues/detail?id=232) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=232)

* **Type**:      Defect
* **Date**:      Mar 8, 2012
* **Reporter**:  ccolu...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New

**Comment by oalders** [comment]
LWP::UserAgent provides a `delete` method, which this module inherits.
