### ISSUE TITLE
setting max_size returns nonsense for content

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#213]
violapir...@gmail.com reported on Jun 12, 2012 

<pre>
<b>What steps will reproduce the problem?</b>
1. $mech-&gt;max_size(1024);
2. $mech-&gt;get($url);
3. print $mech-&gt;content;

Since this is a subclass of LWP::UserAgent, what should be shown is all of the content up until it hit (approximately) 1024 bytes. However, instead what is shown is something like this:

?|???-???+&quot;?O&lt;?p}?,?ܙmW ?`E??\\ސ???ѧ??U{3???

Whenever I do this exact same process with LWP::UserAgent, it gives me actual content. As a subclass I would think WWW::Mechanize would do the same thing.

I am using version 1.66 and I am on centos5.5

</pre>

### Details

Imported from [Google Code issue 236](http://code.google.com/p/www-mechanize/issues/detail?id=236) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=236)

* **Type**:      Defect
* **Date**:      Jun 12, 2012
* **Reporter**:  violapir...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New

**Comment by oalders** [comment]
This appears to be a quirk with how compressed data is handled in LWP vs Mech.  I don't see how `max_size` enters into it.
