### ISSUE TITLE
get() giving 500 and object errors

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#217]
ch...@chrisduffin.org reported on Oct 31, 2012 

<pre>
Hello,

So I recently created a script that get&#39;s a login page, fills out the form, and submits it, in order to test the functionality on a website. This code works perfectly fine on my desktop, however, when running it on my server, the get request seems to fail (with a 500 error) and I get a number of errors about missing or undefined object.

code snippet:

sub canLogin
{

	$mech-&gt;get($loginurl);
	$mech-&gt;save_content( &#39;login.html&#39; );
	print &quot;Status code:&quot;.$mech-&gt;status().&quot;\n&quot;;
	if($@)
	{ 
		$loginfail = 1;
		return &quot;Could not load login page - Status Code: &quot;.$mech-&gt;status();
	}
	print $mech-&gt;text();
	$mech-&gt;cookie_jar(HTTP::Cookies-&gt;new());
	$mech-&gt;form_id(&#39;login-form&#39;);
	$mech-&gt;field (&#39;username&#39; =&gt; $username);
	$mech-&gt;field (&#39;password&#39; =&gt; $password);
	eval { $mech-&gt;submit() };
	$logintime = $mech-&gt;client_total_time;
	if($@)
	{
		$loginfail = 1;
		return &quot;Could not login - Status Code: &quot;.$mech-&gt;status();
	}
	if(index($mech-&gt;text(), &quot;Login failed&quot;) != -1)
	{
		$loginfail = 1;
		return &quot;Page loaded fine but login failed, check credentials. &quot;;
	}
	return &quot;Login succeded: $logintime ms :- &quot;;
}

On my desktop, this produces the following output:

Status code:200
Text content from page

On the server, I get

Status code:500
 There is no form with ID &quot;login-form&quot; at ./check_boards_func line 52.
Can&#39;t call method &quot;value&quot; on an undefined value at /usr/local/share/perl/5.14.2/WWW/Mechanize.pm line 1407.
Can&#39;t locate object method &quot;new&quot; via package &quot;LWPx::TimedHTTP::https::Socket&quot; at /usr/local/share/perl/5.14.2/LWP/Protocol/http.pm line 31.

Both machines have the WWW::Mechanize and WWW::Mechanize::Timed modules installed, as well as LWPx::TimedHTTP::https, and both are running Ubuntu 12.04 x64.

Both using 

WWW::Mechanize	1.72
WWW::Mechanize::Timed	0.44

</pre>

### Details

Imported from [Google Code issue 240](http://code.google.com/p/www-mechanize/issues/detail?id=240) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=240)

* **Type**:      Defect
* **Date**:      Oct 31, 2012
* **Reporter**:  ch...@chrisduffin.org
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New

### Comments
**kabac...@gmail.com** commented on Feb 4, 2013 :

<pre>
Did you ever Got this resolved ?
</pre>

**Comment by oalders** [comment]
I don't think we would be able to reproduce this.
