### ISSUE TITLE
Support for class and id attrs for find_image

### ISSUE THREAD

**Issue by pstray** [libwww-perl/WWW-Mechanize#242]
Would be nice if find_image would support filtering for class and id attributes.

**Comment by simbabque** [comment]
@oalders I would like to grab this one, too.

**Comment by oalders** [comment]
@simbabque consider it yours! 👍

**Comment by simbabque** [comment]
It will come with a large rework of the image tests. There is a lot of duplication and it seems the entire image finding has no coverage.

**Comment by oalders** [comment]
That makes me realize that we should see about getting coverage tests running on this dist.

**Comment by simbabque** [comment]
The things we do for a t-shirt... :)
