### ISSUE TITLE
Bugtracker is Google Code

### ISSUE THREAD

**Issue by Altreus** [libwww-perl/WWW-Mechanize#25]
https://github.com/libwww-perl/WWW-Mechanize/blob/master/Makefile.PL#L79

Google Code is gone :(

**Comment by kentfredric** [comment]
:+1: Down with the googs.

**Comment by epa** [comment]
Please could you also update the View/Report Bugs link shown in http://search.cpan.org/~ether/WWW-Mechanize-1.75/

**Comment by oalders** [comment]
Fixed via b5fd2a651d
