### ISSUE TITLE
Maybe add strict_forms and verbose_forms to object instantiation

### ISSUE THREAD

**Issue by oalders** [libwww-perl/WWW-Mechanize#255]
These could be set to enable`strict` and `verbose` on new `HTML::Form` objects.  These could then be overridden on a case by case basis.  This would make it much easier to enforce best practices, rather than have to set `strict_forms` each time when calling `submit_form`.

**Comment by simbabque** [comment]
I'm almost done implementing this. Will provide a PR shortly.
