### ISSUE TITLE
Fix Pod errors

### ISSUE THREAD

**Issue by oalders** [libwww-perl/WWW-Mechanize#260]
The following errors were encountered while parsing the POD:

Around line 3062:
Unknown directive: =over4

Around line 3064:
'=item' outside of any '=over'

**Comment by simbabque** [comment]
In what branch? Master doesn't have a `=over4`.

**Comment by oalders** [comment]
This is taken directly from the bottom of https://metacpan.org/pod/WWW::Mechanize  It's quite possible that one or both of the problems have been resolved.
