### ISSUE TITLE
Please remove dependency on Perl::Critic

### ISSUE THREAD

**Issue by cpansprout** [libwww-perl/WWW-Mechanize#267]
All tests pass without it installed.  Listing it in the dependencies just adds a several more modules to the list of things to install, when I don’t even need them.

**Comment by oalders** [comment]
Right, this should be in the `develop` prereqs.

**Comment by simbabque** [comment]
I added those in 6049b59f3606c9e415792de9bd29a3ff973d290e to fix tests failing on Travis. I'll move it to `develop`.
