### ISSUE TITLE
find_image* emits warning if $image->url is undef

### ISSUE THREAD

**Issue by kenyapcomau** [libwww-perl/WWW-Mechanize#269]
perl-WWW-Mechanize-1.75

If an img element doesn't have a src url this warning is emitted:

`Use of uninitialized value in pattern match (m//) at /usr/lib/perl5/vendor_perl/5.26.1/WWW/Mechanize.pm line 1217.`

The line in this version is:

`return if defined $p->{url_regex}     && !($image->url =~ $p->{url_regex} );`

It seems that the page in question uses some img elements with no src attribute but a data-image attribute which Javascript processes.

Therefore a guard condition like for alt attributes should be added.

**Comment by oalders** [comment]
Thanks for reporting this.  We would accept a patch to fix it. :)

**Comment by kenyapcomau** [comment]
--- Mechanize.pm.orig   2015-06-03 13:23:58.000000000 +1000
+++ Mechanize.pm        2019-01-15 15:51:15.873534079 +1100
@@ -1213,10 +1213,10 @@
     # No conditions, anything matches
     return 1 unless keys %$p;
 
-    return if defined $p->{url}           && !($image->url eq $p->{url} );
-    return if defined $p->{url_regex}     && !($image->url =~ $p->{url_regex} );
-    return if defined $p->{url_abs}       && !($image->url_abs eq $p->{url_abs} );
-    return if defined $p->{url_abs_regex} && !($image->url_abs =~ $p->{url_abs_regex} );
+    return if defined $p->{url}           && !(defined($image->url) && $image->url eq $p->{url} );
+    return if defined $p->{url_regex}     && !(defined($image->url) && $image->url =~ $p->{url_regex} );
+    return if defined $p->{url_abs}       && !(defined($image->url_abs) && $image->url_abs eq $p->{url_abs} );
+    return if defined $p->{url_abs_regex} && !(defined($image->url_abs) && $image->url_abs =~ $p->{url_abs_regex} );
     return if defined $p->{alt}           && !(defined($image->alt) && $image->alt eq $p->{alt} );
     return if defined $p->{alt_regex}     && !(defined($image->alt) && $image->alt =~ $p->{alt_regex} );
     return if defined $p->{tag}           && !($image->tag && $image->tag eq $p->{tag} );

**Comment by kenyapcomau** [comment]
[m.txt](https://github.com/libwww-perl/WWW-Mechanize/files/2758090/m.txt)

**Comment by simbabque** [comment]
I've grabbed this.
