### ISSUE TITLE
Refers to eliminated WWW-CheckSite in Cookbook

### ISSUE THREAD

**Issue by kentfredric** [libwww-perl/WWW-Mechanize#28]
https://github.com/libwww-perl/WWW-Mechanize/blob/master/lib/WWW/Mechanize/Cookbook.pod#check-all-pages-on-a-web-site 

WWW::CheckSite has vanished, suspected deprecated indefinately;

https://rt.cpan.org/Ticket/Display.html?id=106754

**Comment by genio** [comment]
Thanks for pointing that out.  The out of date information has been removed with 59bd10e
