### ISSUE TITLE
Failed to run on IDN domain name

### ISSUE THREAD

**Issue by aponomarenko** [libwww-perl/WWW-Mechanize#325]
Hello!

All works fine with standard domain names. But for the international domain name I get:

```
Error GETing https://xn--agb0uh1idcdb.xn-----eabag7ad7b4a86af9a0ao5dfm6boib51bbbbcbbcbbbegqkbdbbb.xn--ai3ub/index.php?action=login2;sa=check;member=11020: Can't connect to xn--agb0uh1idcdb.xn-----eabag7ad7b4a86af9a0ao5dfm6boib51bbbbcbbcbbbegqkbdbbb.xn--ai3ub:443 (Name or service not known) at robot.pl line 27.
```

Code:
```
#!/usr/bin/perl

use Encode qw(decode);
use WWW::Mechanize;
use IO::Socket::SSL;
use HTTP::Cookies;

my $FORUM = "https://форум.школа-женского-счастья.рф";

$Mech = WWW::Mechanize->new();
$Mech->cookie_jar(HTTP::Cookies->new());
$Mech->get(decode("UTF-8", $FORUM)."/index.php");
$Mech->form_id("guest_form");
    
$Mech->field("user", "..."));
$Mech->field("passwrd", "...");
$Mech->click;
```

`$Mech->get` works, but `$Mech->click` doesn't. It's trying to get `xn--agb0uh1idcdb.xn-----eabag7ad7b4a86af9a0ao5dfm6boib51bbbbcbbcbbbegqkbdbbb.xn--ai3ub`, but punnycode of my domain name is `xn--l1adgmc.xn-----6kccnlg3aef0aghb5bfbs6ge7h0c.xn--p1ai`. Looks like punnycoding doesn't work. How to workaround this?

I'm using latest version of WWW-Mechanize 2.05 on Fedora 34.

Looking forward for your help.

**Comment by lathropd** [comment]
This should probably be closed…

**Comment by oalders** [comment]
Thanks, everyone!
