### ISSUE TITLE
Mention format of dump_forms

### ISSUE THREAD

**Issue by jidanni** [libwww-perl/WWW-Mechanize#33]
At 
 $mech->dump_forms( [$fh] )
       Prints a dump of the forms on the current page to $fh.  If $fh is not
       specified or is undef, it dumps to STDOUT.

Please also mention the format of the dump, e.g., "ad-hoc".

**Comment by simbabque** [comment]
This was done with c4bcc95. Thanks @kyzn.

**Comment by kyzn** [comment]
I think this was @beppu's commit, so thanks to him 🙂
