### ISSUE TITLE
Say $mech->submit submits current form, not "the page"

### ISSUE THREAD

**Issue by jidanni** [libwww-perl/WWW-Mechanize#34]
Don't you mean "Submits the CURRENT FORM" not "the page"?

=head2 $mech->submit()

Submits the page, without specifying a button to click.  Actually,
no button is clicked at all.
...
    my $request = $self->current_form->make_request;

**Comment by oalders** [comment]
Doc patch welcome!

**Comment by oalders** [comment]
Closed via #114
