### ISSUE TITLE
mech-dump --all should add a title to each section of output 

### ISSUE THREAD

**Issue by jidanni** [libwww-perl/WWW-Mechanize#35]
$ man mech-dump
--all                  Dump all four of the above, in that order

Well OK, but in the output you should say
headers:
....
forms:
....
links:
.....
images:
....

else it is hard to tell them apart sometimes.

Always have all four titles too, even if only three are present.

libwww-mechanize-perl:
  Installed: 1.75-1

**Comment by oalders** [comment]
I would accept a patch for this.
