### ISSUE TITLE
no way to avoid Wide character warnings with mech-dump

### ISSUE THREAD

**Issue by jidanni** [libwww-perl/WWW-Mechanize#36]
Often the user will get this error message

$ mech-dump https://m.facebook.com | head
Wide character in print at /usr/share/perl5/WWW/Mechanize.pm line 2223.
POST https://m.facebook.com/login.php?refsrc=https%3A%2F%2Fm.facebook.com%2F&lwv=100&refid=8
  lsd=AVpaPweT                   (hidden readonly)
  charset_test=€,´,€,´,水,Д,Є     (hidden readonly)...

But there is nothing he can do about it, because  all  the binmode etc. stuff happens under the hood beyond his control.

libwww-mechanize-perl:
  Installed: 1.75-1

**Comment by jidanni** [comment]
$ mech-dump https://fetlife.com/users/sign_in
Wide character in print at /usr/share/perl5/WWW/Mechanize.pm line 2223.
POST https://fetlife.com/users/sign_in
  utf8=✓                         (hidden readonly)
  authenticity_token=J1eCArL+xUqRCNpenJJowj2t6lkkO3EyqOFicOkar5c3IlABwqa1iIALRCjMuW9ajYbiiIpCcJ3Ur3Cw6kbHMQ== (hidden readonly)
  user[login]=                   (text)
  user[password]=                (password)
  user[remember_me]=0            (hidden readonly)
  user[remember_me]=<UNDEF>      (checkbox) [*<UNDEF>/off|1]
  commit=Login to FetLife        (submit)

**Comment by genio** [comment]
This issue has been corrected via PR#56

Thank you!
