### ISSUE TITLE
VERY slow on xpath getting TDs of a TR

### ISSUE THREAD

**Issue by aimass** [libwww-perl/WWW-Mechanize#362]
Hi there!

If there's a mailing list pls. let me know and I'll post the discussion there.

This is taking 2 to 3 seconds on average:
my @cells = $mech->xpath('.//td', node => $rows[$row_index]);

 what is making it so slow ?? Is there a way to speed this?

TIA!

-- 
Alex

**Comment by MartinMcGrath** [comment]
Should be raised under the WWW::Mechanize::Chrome issue tracker: https://github.com/Corion/WWW-Mechanize-Chrome/issues

Context: https://perlmonks.org/?node_id=11148377

**Comment by aimass** [comment]
Sorry, posted on the wrong repo !
