### ISSUE TITLE
click_button dies with coordinates

### ISSUE THREAD

**Issue by hubandr** [libwww-perl/WWW-Mechanize#369]
.. because "x" and "y" are counted as "present exclusive options" and therefore the count of exclusive options is higher than 1.

fixes could be one of these:

https://github.com/hubandr/WWW-Mechanize/tree/fix-click_button-non-exclusive-attributes
https://github.com/hubandr/WWW-Mechanize/tree/fix-click_button-non-exclusive-attributes-2

**Comment by oalders** [comment]
Wonderful! Could you create PRs for both of those? That will make them easier to run under CI, review and see which one we'd like to merge.

Happy New Year!

**Comment by hubandr** [comment]
Happy New Year!

You have two PR now. Thanks.

**Comment by haarg** [comment]
#371 looks fine to me.

**Comment by oalders** [comment]
Closed via #371
