### ISSUE TITLE
Possible "Use of uninitialized value in open" warning in _taintedness

### ISSUE THREAD

**Issue by eserte** [libwww-perl/WWW-Mechanize#382]
The `LWP::ConsoleLogger` test suite fails on some of my smoker systems, caused by a warning originating in `WWW::Mechanize`:
```
Use of uninitialized value in open at /opt/perl-5.41.5/lib/site_perl/5.41.5/WWW/Mechanize.pm line 1650.
```
It seems that this warning happens because at least one value in `%INC` is undef, which results in an `open` call on an undefined filename.

The undefined value belongs to the `Mojo/Reactor/EV.pm` key and it can also be reproduced by this oneliner:
```
$ perl5.41.5 -MMojo::Reactor -MData::Dumper -e 'Mojo::Reactor::detect(); $Data::Dumper::Sortkeys=1; warn Dumper(\%INC)'
...
          'Mojo/Reactor.pm' => '/opt/perl-5.41.5/lib/site_perl/5.41.5/Mojo/Reactor.pm',
          'Mojo/Reactor/EV.pm' => undef,
          'Mojo/Reactor/Poll.pm' => '/opt/perl-5.41.5/lib/site_perl/5.41.5/Mojo/Reactor/Poll.pm',
...
```

In any case, probably within the `for` loop something like `next if !defined $filename` should be done.

**Comment by oalders** [comment]
Thanks @eserte! Do you happen to have an incantation to reproduce the error via Docker?

**Comment by petdance** [comment]
Didn't we get rid of all the taint stuff?

**Comment by oalders** [comment]
> Didn't we get rid of all the taint stuff?

Apparently not. I guess now would be a good time?

**Comment by petdance** [comment]
I must be losing my mind. What DID we remove taintedness from then?

**Comment by petdance** [comment]
No matter, I'll pull a branch to remove it.

**Comment by eserte** [comment]
If you still need a Dockerfile for reproducing it:
```
# docker build -t perl-test . && docker run perl-test
# https://github.com/libwww-perl/WWW-Mechanize/issues/382
FROM perl:5.41.5-bookworm

# install Mojo::Reactor + Mojo::Reactor::EV (but without EV!)
RUN cpan Mojo

# need to switch to non-root because of https://rt.cpan.org/Ticket/Display.html?id=156367
RUN adduser somebody --shell /bin/bash
USER somebody
ENV SHELL /bin/bash

CMD cpan -t LWP::ConsoleLogger
```
Runs for almost half an hour due to many deps. Best to redirect output to a file, to find the warnings afterwards.

**Comment by petdance** [comment]
See PR #383

**Comment by oalders** [comment]
Thanks, @eserte!
