### ISSUE TITLE
Fails to get action URL correct on self referring https form

### ISSUE THREAD

**Issue by martingjohn** [libwww-perl/WWW-Mechanize#42]
Trying to submit the login form https://www.domainmonster.com/login/ but WWW::Mechanize (v1.75) gets the protocol wrong

```
$ mech-dump https://www.domainmonster.com/login/ | grep POST
POST http://www.domainmonster.com:443/login/
POST https://www.domainmonster.com/register/
```
Note the http instead of https on the first form but it does seem to get the second (non-self-referring) one correct.

HTML::Form gets the correct action

```
#!/usr/bin/env perl
use strict;
use warnings;

use HTML::Form;
my $f=HTML::Form->parse (qq!
<form action="/login/" method="post" id="login">
    <input type="hidden" name="action" id="action" value="dologin" />
    <br style="clear:both;" />
        <dl>
                <img src="/images/login/login-mbr-mnstr.png" alt="login now" class="monsterlog">
        <dt>Email Address:</dt><dd><input type="text" name="username" id="username" class="inLng" /></dd>
        <dt>Password:</dt><dd><input type="password" name="password" id="password"  class="inMid" autocomplete="off" /></dd>
        </dl>
        <p>Please note that passwords are case-sensitive.</p>
        <p><input type="submit" value="" class="loginSubmitButton" /></p>
        </form>
!,"https://www.domainmonster.com/login/");

my $a=$f->action;
print "Action - $a\n";
```

Prints

`Action - https://www.domainmonster.com/login/`

As expected

Obviously, this issue stops the form submission working unless I manually fix the action in the form to the right URL

**Comment by oalders** [comment]
Could you run your code with the following?

```perl
use LWP::ConsoleLogger::Easy qw( debug_ua );
use WWW::Mechanize;
 
my $mech = WWW::Mechanize->new;
my $logger = debug_ua( $mech );
```

and then update this ticket with the output?

**Comment by martingjohn** [comment]
Interestingly it's working now

`$ mech-dump https://www.domainmonster.com/login/ | grep POST
POST https://www.domainmonster.com:443/login/
POST https://www.domainmonster.com/register/`

I thought it was with the new version of WWW::Mechanize, I'm now on v1.79 but it worked even when I installed v1.75.

When I added the debug in, I did notice an unusual behaviour with the website, where it seems to keep redirecting between the http://www.domainmonster.com/login/ page and the https version https://www.domainmonster.com/login/

`$ curl https://www.domainmonster.com/login/
<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="http://www.domainmonster.com/login/">here</a></body>
$ curl http://www.domainmonster.com/login/
<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="https://www.domainmonster.com/login/">here</a></body>`

And Chrome sometimes refuses to load it with a complaint about too many redirects. Although this doesn't happen all the time.

Thanks for looking into it, I think I need to ask the webmaster of the site why it sometimes falls into a redirect loop. If I can get it to do it again, I'll run the debug.
