### ISSUE TITLE
provide a means to inspect history

### ISSUE THREAD

**Issue by rjbs** [libwww-perl/WWW-Mechanize#43]
The mech docs say:

> Mech also stores a history of the URLs you've visited, which can
> be queried and revisited.

This is a pretty big overstatement.  The only real access to history is `->back`.

I propose to add a method `$mech->history($n)` which will return the nth history item since current.  If `$n` is zero, it will return the most recent history item, and otherwise it will index `-$n` into the history stack.

The history item will be returned as a hashref like this: `{ req => $http_req, res => $http_res }`

I will also add `$mech->history_count` which will be the number of items in history.  That way, you could iterate `(0 .. $history_count - 1)` for all useful values to pass to `->history`.

If this sounds good, I will write a patch.

**Comment by oalders** [comment]
@rjbs sounds great!

**Comment by ribasushi** [comment]
`history_count` sounds off, surely `history_depth` ...?

**Comment by oalders** [comment]
`history_count` does make it clear that an integer is going to be returned.  `history_depth` doesn't seem quite as obvious to me.  Having said that, I'm all for arguments about naming!  ;)

**Comment by rjbs** [comment]
On their own, I don't think one is wrong and the other right.  I think they're both adequate.  For the record, I picked `count` after also weighing `depth` for two reasons:

* `count` is, to my ear, just a bit clearer (it is purely a number of units in a collection)
* `depth` is already used in `stack_depth`, with an off-by-one meaning compared to this; the `history` method treats the current page as item 0, meaning that the history count is (more or less) `stack_depth` + 1.  I thought that calling them both `depth` would increase the chances of confusion.

**Comment by ribasushi** [comment]
I was not aware of `stack_depth` existing, I concur that `history_depth` would then clash logically. Ignore me.

**Comment by oalders** [comment]
Closed via #44
