### ISSUE TITLE
Live test can't lookup del.icio.us

### ISSUE THREAD

**Issue by Altreus** [libwww-perl/WWW-Mechanize#57]
This seems to be an intermittent failure, but very frustrating when trying to build a Docker container as it requires starting from scratch. Must it cast out to the wider internet?

**Comment by oalders** [comment]
We could make this an author test.  I'd be happy to merge a PR for that.

**Comment by hercynium** [comment]
I've got a simple fix I'll post shortly. However, I noticed in the changelog that the "live" tests used to be skipped unless a `--live` flag was passed in... Looks like you got rid of that when you made the live tests use `Test::RequiresInternet`, which is fine except for exactly this sort of case, where the target site doesn't go away but does change stuff like SSL config/support, or redirects, or (of course) changes the supported encodings.

Now that I typed all that, I realize these really _should_ be author tests.

I'll post my initial simple fix now, but post another PR making those author tests later today if I don't get swamped here.

**Comment by oalders** [comment]
@hercynium thanks for digging in to this.  Reverting back to author tests for the network calls would be great.

**Comment by hercynium** [comment]
OK, I'll do that as well, and change the test to a site that works, too :)

**Comment by hercynium** [comment]
Not sure how to attach the PR to this issue... it's #58

**Comment by oalders** [comment]
Closed via #58
