### ISSUE TITLE
mention form_with_fields prints warning if no such field found

### ISSUE THREAD

**Issue by jidanni** [libwww-perl/WWW-Mechanize#59]
$mech->form_with_fields( @fields )

       Selects a form by passing in a list of field names it must contain.  If
       there is more than one form on the page with that matches, then the
       first one is used, and a warning is generated.

       If it is found, the form is returned as an HTML::Form object and set
       internally for later used with Mech's form methods such as "field()"
       and "click()".

       Returns undef if no form is found.

**And also prints a warning!**

**Comment by genio** [comment]
Thank you for pointing this out.  It has been addressed via 0681198 and will go out with the next release.
