### ISSUE TITLE
Document how to see what will be sent without actually sending anything

### ISSUE THREAD

**Issue by jidanni** [libwww-perl/WWW-Mechanize#61]
I did it! I figured out how to show what will be sent on a request
without actually sending anything!

```
use WWW::Mechanize;
my $mech = WWW::Mechanize->new();
$mech->add_handler("request_send", sub { shift->dump; exit; });
$mech->get("http://www.example.com");
```

(Important when you don't want to create any suspicious traffic while
perfecting your program.) Please document it.

**Comment by oalders** [comment]
We'd accept a pull request for this.
