### ISSUE TITLE
Not all HTML files end in .html, so allow a way to deal with others, other than changing the filename

### ISSUE THREAD

**Issue by jidanni** [libwww-perl/WWW-Mechanize#63]
$ mech-dump file
file:///.../file returns type "text/plain", not "text/html"

For cases like these, please offer a 
>    -T type
>>           explicit characterization of input data by MIME type

like w3m does.

So the user could do
$ mech-dump -T text/html file
to override what mech-dump assumes.

**Comment by jidanni** [comment]
This line in mech-dump
```
$mech->is_html or die qq{$uri returns type "}, $mech->ct, qq{", not "text/html"\n};\
```
means there is no way to use mech-dump with any local file that doesn't end with ".html".
So please add a flag to disable it.

Compare
```
$ lynx -force_html
$ w3m -T type/html
```
I don't see @sergeyromanov 's changed having been merged.

**Comment by jidanni** [comment]
All I know is today I am using 2.03 on Debian, and looking at
https://github.com/libwww-perl/WWW-Mechanize/blob/master/script/mech-dump
I don't see any way to get around
```
file:///home/.../dft112.aspx returns type "text/plain", not "text/html"
```
other than crazy workaround
```
$ ln dft112.aspx dft112.html
```

**Comment by petdance** [comment]
Rather than passing a content-type, I'd suggest mech-dump assume that any file from the filesystem that you dump is valid text/html, so don't check the content-type.
