### ISSUE TITLE
Bad Test, "t/local/failure.t",  tries to look up an existing domain, not a "non-existing one" as it states.

### ISSUE THREAD

**Issue by Astara** [libwww-perl/WWW-Mechanize#73]
Installed WWW::Mechanize-1.83.
It failed to run the above bad test, because it does a bad test for an existing domain.
It runs:
  my $NONEXISTENT = 'blahblahblah.xx-only-testing.foo'; 
  my @results = gethostbyname( $NONEXISTENT );
Test output:
t/local/failure.t .......... skipped: Your ISP is overly helpful and returns 173.164.175.65 for non-existent domain blahblahblah.xx-only-testing.foo. This test cannot be run.

Since the query doesn't append a dot (or period), the query is relative to the current domain and
correctly returns the external gateway address of the domain.  

In order to look up a hostname with "foo" as the TLD, you need to append a period to the hostname in your call to gethostbyname.  I.e.:
  # (note period after "foo")
  my $NONEXISTENT = 'blahblahblah.xx-only-testing.foo.'; 

Cheers!

**Comment by oalders** [comment]
@Astara thanks!
