### ISSUE TITLE
HTML::Form does not work well with Mechanize response objects [rt.cpan.org #54233]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/WWW-Mechanize#96]
Migrated from [rt.cpan.org#54233](https://rt.cpan.org/Ticket/Display.html?id=54233) (status was 'open')

Requestors:
* ilugid@gmail.com

From ilugid@gmail.com on 2010-02-02 21:19:50:
```
The below code tends to work with response objects from LWP::Useragent, 
however for WWW::Mechanize response object, it simply throws an error 

"HTML::Form::parse: No $base_uri provided at ./test.pl line 49"

--------------Sample-Code-------------------------------
my $forms = HTML::Form->parse( "$formresponse" );
my $value = $forms->find_input('SetShift')->value;
print $value;
\\-----------Sample-Code-----------------------------\\

Moreover "$forms->attr( 'SetShift' )" does not seem to be a shortcut to 
saying "$forms->find_input('SetShift')->value" as mentioned in the 
documentation. 
```

From ether@cpan.org on 2017-01-25 21:37:33:
```
migrated queue: libwww-perl -> WWW-Mechanize
```

**Comment by simbabque** [comment]
This works as intended. The sample code provided by OP stringifies the response object, so it's not a reference any more. `HTML::Form::parse` then assumes it is HTML content and requires a `base` object. This happens for HTTP::Response objects from both LWP::UserAgent and WWW::Mechanize. See my marks below.

>                                                     
> ```
>                                V             V
> my $forms = HTML::Form->parse( "$formresponse" );
> my $value = $forms->find_input('SetShift')->value;
> print $value;
> 
> ```

We can easily reproduce this.

```
use LWP::UserAgent;
use HTML::Form;

my $res = LWP::UserAgent->new->get("https://metacpan.org/");
my @forms = HTML::Form->parse("$res");

# HTML::Form::parse: No $base_uri provided at foo.pl line 5.
```

And similarly with Mechanize:

```
use WWW::Mechanize;
use HTML::Form;

my $res = WWW::Mechanize->new->get("https://metacpan.org/");
my @forms = HTML::Form->parse("$res");

# HTML::Form::parse: No $base_uri provided at foo.pl line 5.
```

But without the quotes, it works:

```
use WWW::Mechanize;
use HTML::Form;

my $res = WWW::Mechanize->new->get("https://metacpan.org/");
my @forms = HTML::Form->parse($res);
print scalar @forms;

# 2
```

This is due to a user error. The ticket can be closed.

**Comment by oalders** [comment]
Thanks @simbabque!
